### ISSUE TITLE
Unfollow Class

### ISSUE THREAD

**Issue by Jester565** [Tryst480/syllashare-django#10]
Request:
```
POST api/unfollowclass
{
  "classID": "13424"
}
```
Response: ```{}```

Users submits request to unlink class from calendars

**Comment by NinjaNed** [comment]
are you gonna pass the user_id associated with this request?

**Comment by NinjaNed** [comment]
this is done. ready for testing @JustinCorcuera. @Jester565 make sure you wrap your json keys in quotes.
