### ISSUE TITLE
User Search

### ISSUE THREAD

**Issue by Jester565** [Tryst480/syllashare-django#4]
Request: ```GET api/searchusers?query="Ale"```
Response: 
```
[
  {
    id,
    firstname,
    lastname,
    username,
    profilePicUrl
  }
]
```

The users you return should contain the string "Ale" in the username, firstname, or lastname.  Order responses by string similarity.

Target Date: 10/29/18

**Comment by NinjaNed** [comment]
I've updated this. Please add testing to this @JustinCorcuera
