### ISSUE TITLE
Class Get

### ISSUE THREAD

**Issue by Jester565** [Tryst480/syllashare-django#6]
Request: ```GET api/class?subject"CS"&number="3960"```
Response: 
```
{
  name: "Software Engineering",
  classes: [ {
        classID: "1414",
        teacher: {
         name: "Yu Sun"
       }
  ]
}
```
Target Date: 11/2/18

**Comment by NinjaNed** [comment]
you will need to put the school as well in the url string. Probably as the Primary Key to that School table.
